#!/bin/sh

if [ "$(id -u)" = 0 ]
then
  echo "Don't run this as root, root will be called once needed."
  exit 1
fi

# Launches Steam-BSD-Runtime configurator application
configurator_shortcut() {
    fetch -o ~ https://raw.githubusercontent.com/es-j3/Steam-BSD-Runtime/refs/heads/main/src/icon.png
    xdg-icon-resource install --size 256 ~/icon.png steam-bsd-runtime-configurator --novendor
    touch ~/.local/share/applications/Steam-BSD-Runtime-Configurator.desktop
    chmod +x ~/.local/share/applications/Steam-BSD-Runtime-Configurator.desktop
    sh -c 'echo "[Desktop Entry]
Comment=Launches Steam-BSD-Runtime configurator application
Exec=steam-bsd-runtime-configurator
Icon=steam-bsd-runtime-configurator
Categories=Game;
Name=Steam BSD Runtime Configurator
StartupNotify=false
Terminal=false
TerminalOptions=
Type=Application" > ~/.local/share/applications/Steam-BSD-Runtime-Configurator.desktop'
    rm -rf ~/icon.png
}

# Launches Steam with OSS instead of Pulse (for source games)
oss_shortcut() {
    echo "Adding steam-bsd-runtime-oss to PATH..."
    su -l root -c 'touch /usr/local/bin/steam-bsd-runtime-oss'
    echo "Filling launcher contents..."
    su -l root -c 'echo "WINEPREFIX=~/.proton WINE=/usr/local/wine-proton/bin/wine winetricks sound=oss && WINEPREFIX=~/.proton /usr/local/wine-proton/bin/wine ~/.proton/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu" > /usr/local/bin/steam-bsd-runtime-oss'
    echo "Making launcher executable..."
    su -l root -c 'chmod +x /usr/local/bin/steam-bsd-runtime-oss'
    touch ~/.local/share/applications/Steam-BSD-Runtime-OSS.desktop
    chmod +x ~/.local/share/applications/Steam-BSD-Runtime-OSS.desktop
    sh -c 'echo "[Desktop Entry]
Comment=Video game store and digital distribution platform among other services (OSS sound service)
Exec=steam-bsd-runtime-oss
Icon=steam
Categories=Game;
Name=Steam (OSS)
StartupNotify=false
Terminal=false
TerminalOptions=
Type=Application" > ~/.local/share/applications/Steam-BSD-Runtime-OSS.desktop'
}

zenity --info --text="Steam will be downloaded to /tmp."

# Downloads Steam to the /tmp directory
fetch -o /tmp/SteamSetup.exe https://cdn.fastly.steamstatic.com/client/installer/SteamSetup.exe

zenity --info --text="Let's install DXVK and required fonts for Steam and video games to function properly, along with creating our prefix."

# Calls the Proton prefix and the Wine path to be used, then installs dxvk to get 3D acceleration, and corefonts so the Steam UI works properly.
WINEPREFIX=~/.proton WINE=/usr/local/bin/wine winetricks dxvk corefonts

zenity --info --text="The next step will install Steam."

# Calls proton prefix and then tells default wine to run SteamSetup.exe in /tmp directory.
WINEPREFIX=~/.proton /usr/local/bin/wine /tmp/SteamSetup.exe

# Detects when SteamSetup.exe closes and then opens a window that prompt you to click OK when the first Updating Steam is finished to kill Wine.
while pgrep -f "SteamSetup.exe" > /dev/null; do
    sleep 1
done

zenity --info --text="Please click OK 5-10 seconds after the Updating Steam window closes!"

# Kills everything wine-related
pkill -f "wineserver"
pkill -f "system32"
pkill -f "Steam.exe
pkill -f "steam.exe"
pkill -f "steamwebhelper.exe"

zenity --info --text="Now, let's add a shortcut for Steam. You will get 3 consecutive root password prompts."

# Creates the local applications directory if it doesn't exist already
mkdir -p ~/.local/share/applications

# Calls super user permissions to create the steam-bsd-runtime application.
echo "Adding steam-bsd-runtime to PATH..."
su -l root -c 'touch /usr/local/bin/steam-bsd-runtime'

# Calls super user to echo the contents of the script.
echo "Filling launcher contents..."
su -l root -c 'echo "WINEPREFIX=~/.proton WINE=/usr/local/wine-proton/bin/wine winetricks sound=pulse && WINEPREFIX=~/.proton /usr/local/wine-proton/bin/wine ~/.proton/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu" > /usr/local/bin/steam-bsd-runtime'

# Makes the script executable
echo "Making launcher executable..."
su -l root -c 'chmod +x /usr/local/bin/steam-bsd-runtime'

# Creates the local application shortcut
touch ~/.local/share/applications/Steam-BSD-Runtime.desktop

# Makes it executable
chmod +x ~/.local/share/applications/Steam-BSD-Runtime.desktop

# Echoes the contents of the application shortcut to make it point to the script
sh -c 'echo "[Desktop Entry]
Comment=Video game store and digital distribution platform among other services
Exec=steam-bsd-runtime
Icon=steam
Categories=Game;
Name=Steam
StartupNotify=false
Terminal=false
TerminalOptions=
Type=Application" > ~/.local/share/applications/Steam-BSD-Runtime.desktop'

if zenity --question --text="Would you like to add an extra application shortcut that launches Steam using the OSS sound server? (Necessary for Audio on many SOURCE games)"; then
    oss_shortcut
else
    zenity --info --text="Alright, let's move on."
fi

if zenity --question --text="Would you like to add a shortcut for the Steam BSD Runtime Configurator?"; then
    configurator_shortcut
else
    zenity --info --text="Alright, let's move on."
fi

if zenity --question --text="Do you want to enable DX12 support?"; then
    WINEPREFIX=~/.proton WINE=/usr/local/wine-proton/bin/wine winetricks vkd3d
else
    zenity --info --text="Alright, let's move on."
fi

# Removes the nonfunctioning shortcut automatically created by Wine
rm -rf ~/.local/share/applications/wine/Programs/Steam/

zenity --info --text="Hello! It appears you have reached the end of the Steam BSD Runtime installer. If you experience any issues, please report them at https://github.com/es-j3/Steam-BSD-Runtime/issues. Thanks for using this program :D"

# Sets the Wineprefix to use pulseaudio instead of ALSA / OSS
WINEPREFIX=~/.proton WINE=/usr/local/wine-proton/bin/wine winetricks sound=pulse

# Patches to make games open in steam (Ripped from Mizutamari)
WINEPREFIX=~/.proton /usr/local/wine-proton/bin/wine $WINEBIN reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\DllOverrides" /v "gameoverlayrenderer" /t "REG_SZ" /d "" /f
WINEPREFIX=~/.proton /usr/local/wine-proton/bin/wine $WINEBIN reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\DllOverrides" /v "gameoverlayrenderer64" /t "REG_SZ" /d "" /f



# Launches Steam finally.
WINEPREFIX=~/.proton /usr/local/wine-proton/bin/wine ~/.proton/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu 
