#!/bin/sh

if [ "$(id -u)" = 0 ]
then
  echo "Don't run this as root, root will be called once needed."
  exit 1
fi

remove_shortcuts() {
  cd ~/
  echo "Removing shortcuts..."
  rm -rf ~/.local/share/applications/steam-bottler-OSS.desktop ~/.local/share/applications/steam-bottler-OSS.desktop ~/.local/share/applications/steam-bottler-Configurator.desktop
  su -l root -c 'rm -rf /usr/local/bin/steam-bottler /usr/local/bin/steam-bottler-oss'
}
remove_proton() {
  cd ~/
  echo "Removing proton prefix..."
  rm -rf ~/.proton 
}

remove_everything() {
  su -l root -c 'pkg remove steam-bottler'
  rm -rf ~/steam-bottler-installer ~/steam-bottler-uninstaller ~/steam-bottler-configurator
}
if zenity --question --text="Are you sure you want to uninstall steam-bottler?"; then
    remove_shortcuts
else
    zenity --info --text="Uninstallation canceled."
fi

if zenity --question --text="Remove the Proton Prefix? Think twice, as this removes ALL of your Steam data."; then
    remove_proton
else
    sleep 1
fi

if zenity --question --text="Now finally, shall we remove the uninstaller and installer script?"; then
    remove_everything
else
    sleep 1
fi
