#!/bin/sh

if [ "$(id -u)" = 0 ]; then
  echo "Don't run this as root, root will be called once needed."
  exit 1
fi

COMMAND="$1"
PROTON_DIR="$HOME/.steam-bottler"

case "$COMMAND" in
  "")
    if [ ! -d "$PROTON_DIR" ]; then
      echo "Looks like steam-bottler isn't installed yet. Install it with 'steam-bottler install'"
      exit 1
    fi
    sh -c 'WINEPREFIX=~/.steam-bottler WINE=/usr/local/wine-proton/bin/wine winetricks sound=pulse && WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine ~/.steam-bottler/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu'
    ;;
  "oss")
    if [ ! -d "$PROTON_DIR" ]; then
      echo "Looks like steam-bottler isn't installed yet. Install it with 'steam-bottler install'"
      exit 1
    fi
    sh -c 'WINEPREFIX=~/.steam-bottler WINE=/usr/local/wine-proton/bin/wine winetricks sound=oss && WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine ~/.steam-bottler/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu'
    ;;

  "install")
    if [ -d "$PROTON_DIR" ]; then
      if ! zenity --question --text="This appears to be already installed. Continue?"; then
        exit 0
      fi
    fi

configurator_shortcut() {
	fetch -o ~ https://raw.githubusercontent.com/es-j3/steam-bottler/refs/heads/main/src/icon.png
	xdg-icon-resource install --size 256 ~/icon.png steam-bottler-configurator --novendor
	touch ~/.local/share/applications/steam-bottler-Configurator.desktop
	chmod +x ~/.local/share/applications/steam-bottler-Configurator.desktop
	sh -c 'echo "[Desktop Entry]
	Comment=Launches steam-bottler configurator application
	Exec=steam-bottler configure
	Icon=steam-bottler-configurator
	Categories=Game;
	Name=steam-bottler Configurator
	StartupNotify=false
	Terminal=false
	TerminalOptions=
	Type=Application" > ~/.local/share/applications/steam-bottler-Configurator.desktop'
	rm -rf ~/icon.png
}

oss_shortcut() {
	touch ~/.local/share/applications/steam-bottler-OSS.desktop
	chmod +x ~/.local/share/applications/steam-bottler-OSS.desktop
	sh -c 'echo "[Desktop Entry]
	Comment=Video game store and digital distribution platform among other services (OSS sound service)
	Exec=steam-bottler oss
	Icon=steam
	Categories=Game;
	Name=Steam (OSS)
	StartupNotify=false
	Terminal=false
	TerminalOptions=
	Type=Application" > ~/.local/share/applications/steam-bottler-OSS.desktop'
}

steam_shortcut() {
	sh -c 'echo "[Desktop Entry]
	Comment=Video game store and digital distribution platform among other services
	Exec=steam-bottler
	Icon=steam
	Categories=Game;
	Name=Steam
	StartupNotify=false
	Terminal=false
	TerminalOptions=
	Type=Application" > ~/.local/share/applications/steam-bottler.desktop'
}

check_install() {
    pkg install -y wine wine-proton zenity winetricks
    /usr/local/share/wine/pkg32.sh install wine-proton wine mesa-dri
}

zenity --info --text="Steam will be downloaded to /tmp."

fetch -o /tmp/SteamSetup.exe https://cdn.fastly.steamstatic.com/client/installer/SteamSetup.exe

if zenity --question --text="Would you like to check that all required dependencies are installed?"; then
    check_install
else
    zenity --info --text="Alright, let's move on."
fi

zenity --info --text="Let's install DXVK and required fonts for Steam and video games to function properly, along with creating our prefix."

WINEPREFIX=~/.steam-bottler WINE=/usr/local/bin/wine winetricks dxvk corefonts

zenity --info --text="The next step will install Steam."

WINEPREFIX=~/.steam-bottler /usr/local/bin/wine /tmp/SteamSetup.exe

while pgrep -f "SteamSetup.exe" > /dev/null; do
    sleep 1
done

zenity --info --text="Please click OK 5-10 seconds after the Updating Steam window closes!"

pkill -f "wineserver"
pkill -f "system32"
pkill -f "Steam.exe"
pkill -f "steam.exe"
pkill -f "steamwebhelper.exe"

if zenity --question --text="Would you like to add a shortcut for Steam?"; then
    steam_shortcut
else
    zenity --info --text="Alright, let's move on."
fi

mkdir -p ~/.local/share/applications

touch ~/.local/share/applications/steam-bottler.desktop

chmod +x ~/.local/share/applications/steam-bottler.desktop

sh -c 'echo "[Desktop Entry]
	Comment=Video game store and digital distribution platform among other services
	Exec=steam-bottler
	Icon=steam
	Categories=Game;
	Name=Steam
	StartupNotify=false
	Terminal=false
	TerminalOptions=
	Type=Application" > ~/.local/share/applications/steam-bottler.desktop
'

if zenity --question --text="Would you like to add an extra application shortcut that launches Steam using the OSS sound server? (Necessary for Audio on many SOURCE games)"; then
    oss_shortcut
else
    zenity --info --text="Alright, let's move on."
fi

if zenity --question --text="Would you like to add a shortcut for the steam-bottler Configurator?"; then
    configurator_shortcut
else
    zenity --info --text="Alright, let's move on."
fi

if zenity --question --text="Do you want to enable DX12 support?"; then
    WINEPREFIX=~/.steam-bottler WINE=/usr/local/wine-proton/bin/wine winetricks vkd3d
else
    zenity --info --text="Alright, let's move on."
fi

rm -rf ~/.local/share/applications/wine/Programs/Steam/

zenity --info --text="Hello! It appears you have reached the end of the steam-bottler installer. If you experience any issues, please report them at https://github.com/es-j3/steam-bottler/issues. Thanks for using this program!"

WINEPREFIX=~/.steam-bottler WINE=/usr/local/wine-proton/bin/wine winetricks sound=pulse

WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\DllOverrides" /v "gameoverlayrenderer" /t "REG_SZ" /d "" /f
WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\DllOverrides" /v "gameoverlayrenderer64" /t "REG_SZ" /d "" /f

WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine ~/.steam-bottler/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu 

    ;;

  "configure")
    if [ ! -d "$PROTON_DIR" ]; then
      echo "Looks like steam-bottler isn't installed yet. Install it with 'steam-bottler install'"
      exit 1
    fi
ICO="$HOME/.local/share/icons/hicolor/256x256/apps/steam-bottler-configurator.png"

while true; do
    CHOICE=$(zenity --ok-label="Continue" --cancel-label="Exit" \
        --list --radiolist --window-icon="$ICO" --height=300 --width=400 \
        --title="Steam BSD Runtime Configurator" \
        --text="Configure steam-bottler with one of the following options" \
        --hide-header \
        --column "Select" --column "Option" \
        FALSE "Uninstall" \
	      FALSE "Launch with DXVK HUD" \
        FALSE "Run an EXE" \
        FALSE "Run winetricks" \
        FALSE "Kill steam-bottler if it's frozen" \
        FALSE "Refresh the prefix, make sure wine isnt running" \
        FALSE "Launch Steam with no sound")

    if [ -z "$CHOICE" ]; then
        exit 0
    fi

    case "$CHOICE" in
        "Uninstall")
            steam-bottler remove
            ;;

	"Launch with DXVK HUD")
if ! CHOICES=$(zenity --list --title="DXVK_HUD options" \
    --text="Select Dxvk Hud Options ('0' to disable)" \
    --checklist \
    --column="Add" --column="Select some DXVK_HUD options (1 is default)" \
    FALSE 1 FALSE devinfo FALSE fps FALSE frametimes \
    FALSE submissions FALSE drawcalls FALSE pipelines FALSE memory \
    FALSE gpupload FALSE version FALSE api FALSE compiler FALSE samplers \
    FALSE full \
    --separator="," \
    --width=600 --height=500); then
    exit
fi

	DXVK_HUD="${CHOICES:-0}"

	env DXVK_HUD="$DXVK_HUD" steam-bottler

	;;

        "Run an EXE")
            EXECUTABLE=$(zenity --file-selection --title="Choose an executable to run")
            if [ -n "$EXECUTABLE" ]; then
                WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine "$EXECUTABLE" -no-cef-sandbox
            fi
            ;;

        "Run winetricks")
            WINEPREFIX=~/.steam-bottler WINE=/usr/local/wine-proton/bin/wine winetricks
            ;;

        "Kill steam-bottler if it's frozen")
            pkill -f "wineserver"
            pkill -f "system32"
            pkill -f "Steam.exe"
            pkill -f "steam.exe"
            pkill -f "steamwebhelper.exe"
            ;;

        "Refresh the prefix, make sure wine isn't running")
            WINEPREFIX=~/.steam-bottler /usr/local/bin/wineboot -u
            WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wineboot -u
            ;;
        "Launch Steam with no sound")
            WINEPREFIX=~/.proton WINE=/usr/local/wine-proton/bin/wine winetricks sound=alsa && WINEPREFIX=~/.steam-bottler /usr/local/wine-proton/bin/wine ~/.steam-bottler/drive_c/Program\ Files\ \(x86\)/Steam/steam.exe -cef-disable-sandbox -cef-disable-gpu-compositing -cef-in-process-gpu 
            ;;
    esac
done

    ;;

  "remove")
    if [ ! -d "$PROTON_DIR" ]; then
      zenity --info --text="Maybe it was never installed in the first place."
      exit 0
    fi
    remove_shortcuts() {
	echo "Removing shortcuts..."
	rm -rf ~/.local/share/applications/steam-bottler-OSS.desktop ~/.local/share/applications/steam-bottler.desktop ~/.local/share/applications/steam-bottler-Configurator.desktop ~/.local/share/icons/hicolor/256x256/apps/steam-bottler-configurator.png
}

remove_proton() {
  echo "Removing proton prefix..."
  rm -rf ~/.steam-bottler 
}

remove_everything() {
  su -l root -c 'pkg remove steam-bottler'
  rm -rf ~/steam-bottler-installer ~/steam-bottler-uninstaller ~/steam-bottler-configurator
}

if zenity --question --text="Are you sure you want to uninstall steam-bottler?"; then
    remove_shortcuts
else
    zenity --info --text="Uninstallation canceled."
fi

if zenity --question --text="Remove the Proton Prefix? Think twice, as this removes ALL of your Steam data."; then
    remove_proton
else
    sleep 1
fi

if zenity --question --text="Now finally, shall we remove the uninstaller and installer script?"; then
    remove_everything
else
    sleep 1
fi
    ;;

  *)
    echo "steam-bottler (run this plain to launch Steam) [oss|install|configure|remove]"
    exit 1
    ;;
esac
